### ISSUE TITLE
Reporte de diseño de objeto en 3D

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo-jaciel#2]
[Reporte de Objeto 3D-.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo-jaciel/files/8241793/Reporte.de.Objeto.3D-.pdf)

**Comment by 10154** [comment]
El trabajo cumple con todos los puntos mencionados en la rúbrica, obteniendo un porcentaje del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
